property_name: [property, building, community, asset name]
address: [address, street, addr]
city: [city, town]
state: [state, province, st]
zip: [zip, postal]
unit_id: ["unit","apt","apartment","suite","space","unit #","unit number"]

tenant_name: [tenant, resident, name, renter, lessee, occupant]
email: [email,"e-mail"]
phone: [phone,tel,telephone,mobile]
move_in: ["move in","lease start","start","start date"]
move_out: ["move out","lease end","end","end date"]
deposit: [deposit,secdep,"security deposit"]
status: [status,eviction,delinquent,vacant,occupied]

period: [month,period,date,"as of",posted]
income: [income,rent,revenue,"other income","gross income",collections]
expense: [expense,"operating expense",opex,maintenance,repairs,utilities]
noi: [noi,"net operating income"]
capex: [capex,"capital expenditures"]
taxes: [tax,"property tax",taxes]
insurance: [insurance]
mortgage: [mortgage,"debt service","loan payment",principal,interest]
balance: [balance,"ending balance","balance due"]
arrears: [arrears,delinquency,"past due"]
asset: [asset,assets,cash,bank,receivable,prepaid]
liability: [liability,liabilities,payable,loan,note]
equity: [equity,"owner's equity","retained earnings"]
